# node:current-alpine3.17
FROM node@sha256:d0b02b1ec5534efb43a926069915c982aec745a8eb0611ebcffc4cafaa4e4a74

ARG NPM_TOKEN

WORKDIR /app

COPY .npmrc .

COPY package.json .

COPY yarn.lock .

COPY tsconfig.json .

COPY listeners.json .

COPY src src

RUN yarn install

RUN rm .npmrc

RUN npx tsc

RUN ls -l dist/src

# CMD [ "yarn", "start:listener:vrf" ]

# CMD [ "sleep", "3000" ]

ENTRYPOINT ["tail", "-f", "/dev/null"]







# # tiangolo/uvicorn-gunicorn-fastapi:python3.9-slim
# FROM tiangolo/uvicorn-gunicorn-fastapi@sha256:aaaaa83a11913562227067c0c5481beec4d7e5c3001be28d31e926e83fed3e7a

# # TODO setup a user instead of root

# ENV PYTHONUNBUFFERED=1

# WORKDIR /app

# RUN apt-get update && apt-get install curl -y

# COPY backend/provider/requirements.txt /tmp/requirements.txt
# RUN pip install --no-cache-dir -r /tmp/requirements.txt

# COPY backend/common ./common
# COPY backend/provider ./provider
# COPY backend/provider_api.py ./
