import pino from 'pino'
import { LOG_LEVEL } from './settings'

export function buildLogger() {
  const transport = pino.transport({
    targets: [{ target: 'pino-pretty', level: LOG_LEVEL, options: { destination: 1 } }],
  })

  const logger = pino(transport)
  logger.level = LOG_LEVEL

  return logger
}

/**
 * Logger created with this function is expected to be used within
 * tests, however, because of its properties, it can be used also at
 * other places, but it is not recommended. Logs generated by this
 * logger will be send to standard output, and formatted for a better
 * readability.
 */
export function buildMockLogger() {
  const transport = pino.transport({
    targets: [{ target: 'pino-pretty', level: LOG_LEVEL, options: { destination: 1 } }],
  })

  const logger = pino(transport)
  return logger
}
