version: '3.7'

services:
  redis:
    # redis:7.0.5-alpine3.17
    image: redis@sha256:06e4453169faaf4af93fe38689c8f8f85440990f9b9c1e91b0f9f98b1679452a
    container_name: redis_dev
    hostname: redis_dev
    expose:
      - 6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  listener-aggregator:
    image: core-icn
    container_name: listener_aggregator_dev
    hostname: listener_aggregator_dev
    entrypoint: ['yarn', 'start:listener:aggregator']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=production
      - ORAKL_DIR=/app/db
      - CHAIN
      - HEALTH_CHECK_PORT
      - SLACK_WEBHOOK_URL
    healthcheck: &common-healthcheck
      test: 'curl --fail http://localhost:${HEALTH_CHECK_PORT} || exit 1'
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on: &common-depends_on
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ${HOST_SETTINGS_DB_DIR}:/app/db

  worker-aggregator:
    image: core-icn
    container_name: worker_aggregator_dev
    hostname: worker_aggregator_dev
    entrypoint: ['yarn', 'start:worker:aggregator']
    environment:
      - NODE_ENV=production
      - ORAKL_DIR=/app/db
      - CHAIN
      - HEALTH_CHECK_PORT
      - SLACK_WEBHOOK_URL
    healthcheck:
      <<: *common-healthcheck
    depends_on:
      <<: *common-depends_on
    restart: unless-stopped
    volumes:
      - ${HOST_SETTINGS_DB_DIR}:/app/db

  reporter-aggregator:
    image: core-icn
    container_name: reporter_aggregator_dev
    hostname: reporter_aggregator_dev
    entrypoint: ['yarn', 'start:reporter:aggregator']
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NODE_ENV=production
      - ORAKL_DIR=/app/db
      - CHAIN
      - HEALTH_CHECK_PORT
      - SLACK_WEBHOOK_URL
    healthcheck:
      <<: *common-healthcheck
    depends_on:
      <<: *common-depends_on
    restart: unless-stopped
    volumes:
      - ${HOST_SETTINGS_DB_DIR}:/app/db
