version: '3.7'

services:
  bull-monitor:
    image: ejhayes/nodejs-bull-monitor:latest
    ports:
      - 3002:3000
    environment:
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      BULL_WATCH_QUEUE_PREFIXES: bull
      PORT: 3000
      UI: bull-board
    healthcheck:
      test: "curl --fail http://localhost:3002/health || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    restart: unless-stopped
