version: '3.7'

services:
  redis:
    # redis:7.0.5-alpine3.17
    image: redis@sha256:06e4453169faaf4af93fe38689c8f8f85440990f9b9c1e91b0f9f98b1679452a
    container_name: redis_dev
    hostname: redis_dev
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  listener-vrf:
    image: core-icn
    container_name: listener_vrf_dev
    hostname: listener_vrf_dev
    entrypoint: ["yarn", "start:listener:vrf"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HEALTH_CHECK_PORT
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LISTENERS
      - NODE_ENV=production
    healthcheck:
      &common-health-check
      test: "curl --fail http://localhost:${HEALTH_CHECK_PORT} || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis
    restart: unless-stopped

  worker-vrf:
    image: core-icn
    container_name: worker_vrf_dev
    hostname: worker_vrf_dev
    entrypoint: ["yarn", "start:worker:vrf"]
    environment:
      - HEALTH_CHECK_PORT
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LOCAL_AGGREGATOR
      - VRF_SK
      - VRF_PK
      - VRF_PK_X
      - VRF_PK_Y
      - NODE_ENV=production
    healthcheck:
      <<: *common-health-check
    depends_on:
      - redis
    restart: unless-stopped

  reporter-vrf:
    image: core-icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: reporter_vrf_dev
    hostname: reporter_vrf_dev
    entrypoint: ["yarn", "start:reporter:vrf"]
    environment:
      - HEALTH_CHECK_PORT
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - MNEMONIC
      - PUBLIC_KEY
      - PRIVATE_KEY
      - NODE_ENV="production"
    healthcheck:
      <<: *common-health-check
    depends_on:
      - redis
    restart: unless-stopped