version: '3.7'

services:
  redis:
    # redis:7.0.5-alpine3.17
    image: redis@sha256:06e4453169faaf4af93fe38689c8f8f85440990f9b9c1e91b0f9f98b1679452a
    container_name: redis_dev
    hostname: redis_dev
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  listener-vrf:
    image: core_icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LISTENERS
      - NODE_ENV
    container_name: listener_vrf_dev
    hostname: listener_vrf_dev
    entrypoint: ["yarn", "start:listener:vrf"]
    expose:
      - 8888
    healthcheck:
      test: "curl --fail http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  listener-any-api:
    image: core_icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LISTENERS
      - NODE_ENV
    container_name: listener_any_api_dev
    hostname: listener_any_api_dev
    entrypoint: ["yarn", "start:listener:any_api"]
    expose:
      - 8888
    healthcheck:
      test: "curl --fail http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  listener-aggregator:
    image: core_icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LISTENERS
      - NODE_ENV
    container_name: listener_aggregator_dev
    hostname: listener_aggregator_dev
    entrypoint: ["yarn", "start:listener:aggregator"]
    expose:
      - 8888
    healthcheck:
      test: "curl --fail http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  worker-vrf:
    image: core_icn
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LOCAL_AGGREGATOR
      - VRF_SK
      - VRF_PK
      - VRF_PK_X
      - VRF_PK_Y
      - NODE_ENV      
    container_name: worker_vrf_dev
    hostname: worker_vrf_dev
    entrypoint: ["yarn", "start:worker:vrf"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  worker-any-api:
    image: core_icn
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LOCAL_AGGREGATOR
      - VRF_SK
      - VRF_PK
      - VRF_PK_X
      - VRF_PK_Y
      - NODE_ENV      
    container_name: worker_any_api_dev
    hostname: worker_any_api_dev
    entrypoint: ["yarn", "start:worker:any_api"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  worker-aggregator:
    image: core_icn
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LOCAL_AGGREGATOR
      - VRF_SK
      - VRF_PK
      - VRF_PK_X
      - VRF_PK_Y
      - NODE_ENV      
    container_name: worker_aggregator_dev
    hostname: worker_aggregator_dev
    entrypoint: ["yarn", "start:worker:aggregator"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  worker-predefined-feed:
    image: core_icn
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - LOCAL_AGGREGATOR
      - VRF_SK
      - VRF_PK
      - VRF_PK_X
      - VRF_PK_Y
      - NODE_ENV      
    container_name: worker_predefined_feed_dev
    hostname: worker_predefined_feed_dev
    entrypoint: ["yarn", "start:worker:predefined_feed"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  reporter-vrf:
    image: core_icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - MNEMONIC
      - PUBLIC_KEY
      - PRIVATE_KEY
      - NODE_ENV       
    container_name: reporter_vrf_dev
    hostname: reporter_vrf_dev
    entrypoint: ["yarn", "start:reporter:vrf"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  reporter-any-api:
    image: core_icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - MNEMONIC
      - PUBLIC_KEY
      - PRIVATE_KEY
      - NODE_ENV       
    container_name: reporter_any_api_dev
    hostname: reporter_any_api_dev
    entrypoint: ["yarn", "start:reporter:any_api"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis

  reporter-aggregator:
    image: core_icn
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PROVIDER
      - REDIS_HOST
      - REDIS_PORT
      - MNEMONIC
      - PUBLIC_KEY
      - PRIVATE_KEY
      - NODE_ENV       
    container_name: reporter_aggregator_dev
    hostname: reporter_aggregator_dev
    entrypoint: ["yarn", "start:reporter:aggregator"]
    expose:
      - 8888
    healthcheck:
      test: "curl -f  http://localhost:8888/health-check || exit 1"
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      - redis      