version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/grafana/data
