version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:4eaa280
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'https://api.thegraph.com/ipfs/'
      ethereum: 'baobab:https://api.baobab.klaytn.net:8651'
      GRAPH_LOG: info

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - 3000:3000
    restart: unless-stopped

  orakl-monitor:
    image: jolol/orakl-monitor:v.0.0.1
    environment:
      PROVIDER: https://api.baobab.klaytn.net:8651
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: graph-node
    restart: unless-stopped
    depends_on:
      - postgres       