CREATE TABLE IF NOT EXISTS aggregators (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS global_aggregates (
    name TEXT NOT NULL,
    value INT8 NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    round INT8 NOT NULL
)