DELETE FROM peers;
ALTER TABLE peers DROP COLUMN IF EXISTS url;
ALTER TABLE peers ADD COLUMN IF NOT EXISTS ip TEXT;
ALTER TABLE peers ADD COLUMN IF EXISTS port INT4;
ALTER TABLE peers ADD COLUMN IF EXISTS host_id TEXT;