name: ADMIN Deploy to Amazon ECR

on:
  pull_request:
    branches:
      - master
    paths:
      - "admin/**"
    types:
      - closed
# on:
#   push:
#     branches:
#       - i-756/feat/integrate-env-admin

env:
  ecr_url: public.ecr.aws/bisonai/orakl-general

jobs:
  prepare:
    name: Prepare Build Baobab
    runs-on: ubuntu-latest

    outputs:
      tag_date: ${{ steps.tag.outputs.date }}
      tag_git_hash: ${{ steps.tag.outputs.git_hash }}
      version: ${{ steps.package.outputs.version }}

    steps:
      - uses: actions/checkout@v3

      - name: Get time TAG
        id: tag
        run: |
          echo "date=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
          echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get package version
        id: package
        run: |
          echo "version=$(node -p -e "require('./api/package.json').version")" >> $GITHUB_OUTPUT
          
  build-baobab:
    name: Build Baobab
    runs-on: ubuntu-latest
    needs: prepare

    permissions:
      id-token: write
      contents: read 

    outputs:
      tag_date: ${{ steps.tag.outputs.date }}
      tag_git_hash: ${{ steps.tag.outputs.git_hash }}

    steps:
      - uses: actions/checkout@v3

      - name: Docker build orakl-admin-baobab
        run: |
          docker build -t orakl-general-admin-baobab admin/. \
          --build-arg MONITOR_EXTERNAL_URL=http://35.240.192.58:8888 \
          --build-arg DELEGATOR_EXTERNAL_URL=http://34.87.152.175:5050

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public        

      - name: Publish Image to ECR(admin)
        run: |
          docker tag orakl-general-admin-baobab ${{ env.ecr_url }}:admin-baobab.v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}
          docker push ${{ env.ecr_url }}:admin-baobab.v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}

  build-cypress:
    name: Build Cypress
    runs-on: ubuntu-latest
    needs: prepare

    permissions:
      id-token: write
      contents: read 

    outputs:
      tag_date: ${{ steps.tag.outputs.date }}
      tag_git_hash: ${{ steps.tag.outputs.git_hash }}

    steps:
      - uses: actions/checkout@v3

      - name: Docker build orakl-admin-cypress
        run: |
          docker build -t orakl-general-admin-cypress admin/. \
          --build-arg MONITOR_EXTERNAL_URL=http://34.142.143.138:8888 \
          --build-arg DELEGATOR_EXTERNAL_URL=http://34.126.65.247:5050

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public        

      - name: Publish Image to ECR(admin)
        run: |
          docker tag orakl-general-admin-cypress ${{ env.ecr_url }}:admin-cypress.v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}
          docker push ${{ env.ecr_url }}:admin-cypress.v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}