name: "api: test+build"
on:
  push:
    paths:
      - "api/**"
jobs:
  core-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
      - name: Install dependencies
        run: yarn install
        working-directory: ./api
      - name: Run eslint
        run: yarn lint
        working-directory: ./api
      - name: Run test
        run: ./test.sh
        working-directory: ./api
      - name: Run e2e2 test
        run: yarn test:e2e
        working-directory: ./api
      - name: Build package
        run: yarn build
        working-directory: ./api
