name: "cli: build+publish"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "cli/**"

jobs:
  build-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
          registry-url: "https://registry.npmjs.org"
          scope: "@bisonai"
          always-auth: true
      - name: Install dependencies
        run: yarn cli install
      - name: Run lint
        run: yarn cli lint
      - name: Build package
        run: yarn cli build
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: packageJsonVersion
        with:
          cmd: "jq .version ./cli/package.json -r"
      - name: Extract version from the latest published package
        id: npmPackageVersion
        run: echo "VERSION=`npm view @bisonai/orakl-cli version`" >> $GITHUB_OUTPUT
      - name: Check if new version is greater
        id: check-version
        run: |
          npm install -g semver
          echo "isGreater=$(node -e "console.log(require('semver').gt('${{ steps.packageJsonVersion.outputs.value }}', '${{ steps.npmPackageVersion.outputs.VERSION }}'))")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Publish package
        if: steps.check-version.outputs.isGreater == 'true'
        run: yarn cli publish --new-version ${{ steps.packageJsonVersion.outputs.value }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
