name: "cli: build+publish"
on: push
# on:
#   push:
#     paths:
#       - "core/src/cli/orakl-cli/**"
jobs:
  cli-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
          registry-url: "https://registry.npmjs.org"
          scope: "@bisonai"
          always-auth: true
      - name: Install dependencies
        run: yarn --cwd . install
        working-directory: ./core/src/cli/orakl-cli
      - name: Build package
        run: yarn --cwd . build
        working-directory: ./core/src/cli/orakl-cli
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ./core/src/cli/orakl-cli/package.json -r'
      - run: yarn publish --new-version ${{ steps.version.outputs.value }} --access public
        working-directory: ./core/src/cli/orakl-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
