name: "contracts: test+publish"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "packages/contracts/**"
      - "!packages/contracts/**/VRFCoordinator.sol"
      - "!packages/contracts/**/VRFConsumerBase.sol"
      - "!packages/contracts/**/vrf/**"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
          registry-url: "https://registry.npmjs.org"
          scope: "@bisonai"
          always-auth: true
      - run: yarn workspace @bisonai/orakl-contracts install
      - run: yarn workspace @bisonai/orakl-contracts prettier-solidity-check
      - run: yarn workspace @bisonai/orakl-contracts solhint
      - run: yarn workspace @bisonai/orakl-contracts eslint
      - run: yarn workspace @bisonai/orakl-contracts test-non-vrf
        env:
          L2_PROVIDER: ${{ secrets.L2_PROVIDER }}
      - run: yarn workspace @bisonai/orakl-contracts compile
        env:
          L2_PROVIDER: ${{ secrets.L2_PROVIDER }}
      - run: yarn workspace @bisonai/orakl-contracts build
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: packageJsonVersion
        with:
          cmd: "jq .version ./packages/contracts/package.json -r"
      - name: Extract version from the latest published package
        id: npmPackageVersion
        run: echo "VERSION=`npm view @bisonai/orakl-contracts version`" >> $GITHUB_OUTPUT
      - name: Publish package
        if: steps.packageJsonVersion.outputs.value != steps.npmPackageVersion.outputs.VERSION
        run: yarn workspace @bisonai/orakl-contracts publish --new-version ${{ steps.packageJsonVersion.outputs.value }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
