name: "core: test+build"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "packages/core/**"

jobs:
  core-build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Install dependencies
        run: yarn workspace @bisonai/orakl-core install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run lint
        run: yarn workspace @bisonai/orakl-core lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run test
        run: yarn workspace @bisonai/orakl-core test
        env:
          ORAKL_DIR: "./"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CAVER_PRIVATE_KEY: ${{ secrets.CAVER_PRIVATE_KEY}}
      - name: Build package
        run: yarn workspace @bisonai/orakl-core build
