name: "core: test+build"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "core/**"

jobs:
  core-build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Install dependencies
        run: yarn core install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build workspace dependency (vrf)
        run: yarn vrf build
      - name: Build workspace dependency (contracts)
        run: yarn contracts clean && yarn contracts compile && yarn contracts build
      - name: Run lint
        run: yarn core lint
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run test
        run: yarn core test
        env:
          ORAKL_DIR: "./"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CAVER_PRIVATE_KEY: ${{ secrets.CAVER_PRIVATE_KEY}}
      - name: Build package
        run: yarn core build
