name: "core: test+build"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "core/**"

jobs:
  core-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
      - name: Install dependencies
        run: yarn install
        working-directory: ./core
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run eslint
        run: yarn eslint
        working-directory: ./core
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run test
        run: yarn test
        working-directory: ./core
        env:
          ORAKL_DIR: "./"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          CAVER_PRIVATE_KEY: ${{ secrets.CAVER_PRIVATE_KEY}}
      - name: Build package
        run: yarn build
        working-directory: ./core
