name: "core+cli"
on: push
# on:
#   push:
#     paths:
#       - "core/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
      - name: Install dependencies
        run: yarn install
        working-directory: ./core
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run eslint
        run: yarn eslint
        working-directory: ./core
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run test
        run: yarn test
        working-directory: ./core
        env:
          ORAKL_DIR: './'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build package
        run: yarn build
        working-directory: ./core

  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
      - name: Install dependencies
        run: yarn install
        working-directory: ./core/src/cli/orakl-cli
      - name: Build package
        run: yarn build
        working-directory: ./core/src/cli/orakl-cli
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version ./core/src/cli/orakl-cli/package.json -r'
      - name: Show my version
        run: 'echo "version ${{ steps.version.outputs.value }}"'
      # - run: yarn publish --new-version ${{ steps.version.outputs.value }} --access public
      #   working-directory: ./core/src/cli/orakl-cli
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
