name: "miko delegator test"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "node/pkg/delegator/**"
  workflow_dispatch:

jobs:
  core-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: miko-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.3"
          check-latest: true
          cache-dependency-path: |
            ./node/go.sum
      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv ./migrate /usr/bin
      - name: Migrate up
        run: |
          cd ./node
          migrate -database "postgresql://postgres:postgres@localhost:5432/miko-test?search_path=public&sslmode=disable" -verbose -path ./migrations/delegator up
      - name: Install dependencies
        run: |
          cd ./node
          go mod tidy
      - name: Run test
        run: |
          cd ./node/pkg/delegator
          go test ./tests -v
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/miko-test?search_path=public"
          PROVIDER_URL: "https://public-en-kairos.node.kaia.io"
          TEST_DELEGATOR_REPORTER_PK: ${{ secrets.TEST_DELEGATOR_REPORTER_PK}}
          DELEGATOR_FEEPAYER_PK: ${{ secrets.DELEGATOR_FEEPAYER_PK}}
