name: Post to a Slack channel

on:
  workflow_call:
    inputs:
      slack-message:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true            
jobs:
  post-to-slack:
    name: Post a message to a Slack channel
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read 

    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'orakl-notification'
          payload: |
            {
              "text": "${{ inputs.slack-message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.slack-message }}"
                  }
                }
              ]
            } 
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}    