name: Post to a Slack channel

on:
  workflow_call:
    inputs:
      slack-message:
        required: true
        type: string
      status:
        required: true
        type: string
      channel:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true

jobs:
  post-to-slack:
    name: Post a message to a Slack channel
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set Slack Payload
        id: set-payload
        run: |
          if [ "${{ inputs.status }}" == "Success" ]; then
            echo "payload={\"text\":\":white_check_mark: ${{ inputs.slack-message }}\",\"attachments\":[{\"color\":\"28a745\",\"fields\":[{\"title\":\"Status\",\"short\":true,\"value\":\"${{ inputs.status }}\"}]}]}" >> $GITHUB_OUTPUT
          else
            echo "payload={\"text\":\":exclamation: ${{ inputs.slack-message }}\",\"attachments\":[{\"color\":\"E96D76\",\"fields\":[{\"title\":\"Status\",\"short\":true,\"value\":\"${{ inputs.status }}\"}]}]}" >> $GITHUB_OUTPUT
          fi

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ inputs.channel }}
          payload: ${{ steps.set-payload.outputs.payload }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
