name: "request-response: integration-test"

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/integration')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"

      - name: Install
        run: yarn
        working-directory: ./contracts

      - name: Compile
        run: yarn compile
        working-directory: ./contracts

      - name: Build
        run: yarn build
        working-directory: ./contracts

      - name: Run node and deploy
        run: npx hardhat node & npx hardhat deploy
        working-directory: ./contracts

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6

      - name: Core - install
        run: yarn
        working-directory: ./core

      - name: Core - build
        run: yarn build
        working-directory: ./core

      - name: Core - start listener
        run: yarn start:listener:request_response &
        working-directory: ./core

      - name: Request data
        run: npx hardhat run scripts/v0.1/request-response/integration/request-data.ts --network localhost
        working-directory: ./contracts

      - name: Core - start worker
        run: yarn start:worker:request_response &
        working-directory: ./core

      - name: Core - start reporter
        run: yarn start:reporter:request_response &
        working-directory: ./core

      - name: Get data
        run: npx hardhat run scripts/v0.1/request-response/integration/read-data.ts --network localhost
        working-directory: ./contracts
