name: "request-response: integration-test"

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/integration')
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"

      - name: Install
        run: yarn workspace @bisonai/orakl-contracts install

      - name: Compile
        run: yarn workspace @bisonai/orakl-contracts compile

      - name: Build
        run: yarn workspace @bisonai/orakl-contracts build

      - name: Run node and deploy
        run: yarn workspace @bisonai/orakl-contracts setup-local-node

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6

      - name: Core - install
        run: yarn workspace @bisonai/orakl-core install

      - name: Core - build
        run: yarn workspace @bisonai/orakl-core build

      - name: Core - start listener
        run: yarn workspace @bisonai/orakl-core start:listener:request_response &

      - name: Request data
        run: yarn workspace @bisonai/orakl-contracts request-data --network localhost

      - name: Core - start worker
        run: yarn workspace @bisonai/orakl-core start:worker:request_response &

      - name: Core - start reporter
        run: yarn yarn workspace @bisonai/orakl-core start:reporter:request_response &
        env:
          PRIVATE_KEY: ${{ secrets.INTEGRATION_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.INTEGRATION_PUBLIC_KEY }}

      - name: Get data
        run: yarn workspace @bisonai/orakl-contracts get-data --network localhost
