name: "service:npm:trigger"

on:
  push:
    branches:
      - "feat/fix-CI/CD"
    # paths:
    #   - 'cli/package.json'

jobs:

  trigger_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@master

      - name: Trigger Dispatch Deploy
        uses: ./.github/workflows/deployment.yaml
        with:
          application: "cli"
          network: "Baobab"