name: "service:npm:trigger"

on:
  push:
    branches:
      - "feat/fix-CI/CD"
    # paths:
    #   - 'cli/package.json'

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  trigger_deploy:
    name: Trigger Dispatch Deploy
    needs: prepare
    uses: ./.github/workflows/deployment.yaml
    with:
      application: "cli"
      network: "Baobab"
    secrets:
      AT: ${{ secrets.PAT }}
