name: "service:npm:trigger"

on:
  push:
    branches:
      - "feat/fix-CI/CD"
    # paths:
    #   - 'cli/package.json'

jobs:

  trigger_deploy:
    name: Trigger Dispatch Deploy
    uses: .github/workflows/deployment.yaml
    with:
      application: "cli"
      network: "Baobab"
    secrets:
      AT: ${{ secrets.PAT }}
