name: "service:npm:trigger"

on:
  push:
    branches:
      - "feat/fix-CI/CD"
    # paths:
    #   - 'cli/package.json'

jobs:
  post-slack-image-upload:
    name: Slack message for image upload 
    uses: ./.github/workflows/post.slack.yaml
    with:
      status: "Success"
      slack-message: testing"
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}  

  trigger_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Trigger Dispatch Deploy
        uses: ./.github/workflows/deployment.yaml
        with:
          application: "cli"
          network: "Baobab"