name: "vrf: build+publish"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "vrf/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
      - name: Install dependencies
        run: yarn --cwd . install
        working-directory: ./vrf
      - name: Run lint
        run: yarn --cwd . lint
        working-directory: ./vrf
      - name: Build package
        run: yarn --cwd . build
        working-directory: ./vrf

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
          registry-url: "https://registry.npmjs.org"
          scope: "@bisonai"
          always-auth: true
      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: packageJsonVersion
        with:
          cmd: "jq .version ./vrf/package.json -r"
      # - name: Extract version from the latest published package
      #   id: npmPackageVersion
      #   run: echo "VERSION=`npm view @bisonai/orakl-vrf version`" >> $GITHUB_OUTPUT
      - name: Publish package
        # if: steps.packageJsonVersion.outputs.value != steps.npmPackageVersion.outputs.VERSION
        # run: yarn publish --new-version ${{ steps.packageJsonVersion.outputs.value }} --access public
        run: yarn publish --new-version 0.1.0 --access public
        working-directory: ./vrf
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
