name: "contracts-vrf: integration-test"
on:
  push:
    paths:
      - "contracts/**"
    branches:
      - "296-integration-test-for-vrf-onchain-components"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"
      - name: Install
        run: yarn
        working-directory: ./contracts
      - name: Compile
        run: yarn compile
        working-directory: ./contracts
      - name: Build
        run: yarn build
        working-directory: ./contracts
      - name: Run node and Deploy
        run: npx hardhat node & npx hardhat deploy
        working-directory: ./contracts
      - name: Request Randomwords
        run: npx hardhat run scripts/v0.1/vrf/vrf-integration.ts --network localhost
        working-directory: ./contracts
        env:
          GITHUB_ACTIONS: $GITHUB_ACTIONS
