name: "contracts-vrf: integration-test"
on:
  push:
    paths:
      - "contracts/**"
      - "core/**"
    branches:
      - "296-integration-test-for-vrf-onchain-components"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"

      - name: Install
        run: yarn
        working-directory: ./contracts

      - name: Compile
        run: yarn compile
        working-directory: ./contracts

      - name: Build
        run: yarn build
        working-directory: ./contracts

      - name: Run node and Deploy
        run: npx hardhat node & npx hardhat deploy
        working-directory: ./contracts

      - name: Request Randomwords
        run: npx hardhat run scripts/v0.1/vrf/vrf-integration.ts --network localhost
        working-directory: ./contracts
      - name: Install pm2
        run: npm install pm2
      - name: Core - install
        run: yarn
        working-directory: ./core

      - name: Core - build
        run: yarn build
        working-directory: ./core

      - name: Core - start listener
        run: npx pm2 start yarn --name lvrf --interpreter bash -- start:listener:vrf
        working-directory: ./core

      - name: Core - start listener
        run: npx pm2 start yarn --name wvrf --interpreter bash -- start:worker:vrf
        working-directory: ./core

      - name: Core - start listener
        run: npx pm2 start yarn --name rrf --interpreter bash -- start:reporter:vrf
        working-directory: ./core

      - name: Get random words
        run: npx hardhat run scripts/v0.1/vrf/vrf-integration-read.ts --network localhost
        working-directory: ./contracts
