name: "vrf: integration-test"

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/integration')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.12"

      - name: Install
        run: yarn
        working-directory: ./contracts

      - name: Compile
        run: yarn compile
        working-directory: ./contracts

      - name: Build
        run: yarn build
        working-directory: ./contracts

      - name: Run node and deploy
        run: npx hardhat node & npx hardhat deploy
        working-directory: ./contracts

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6

      - name: Core - install
        run: yarn
        working-directory: ./core

      - name: Core - build
        run: yarn build
        working-directory: ./core

      - name: Core - start listener
        run: yarn start:listener:vrf &
        working-directory: ./core

      - name: Request random words
        run: npx hardhat run scripts/v0.1/vrf/integration/request-vrf.ts --network localhost
        working-directory: ./contracts

      - name: Core - start worker
        run: yarn start:worker:vrf &
        working-directory: ./core

      - name: Core - start reporter
        run: yarn start:reporter:vrf &
        working-directory: ./core
        env:
          PRIVATE_KEY: ${{ secrets.INTEGRATION_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.INTEGRATION_PUBLIC_KEY }}

      - name: Get random words
        run: npx hardhat run scripts/v0.1/vrf/integration/read-vrf.ts --network localhost
        working-directory: ./contracts
