name: "vrf: integration-test"

on:
  push:
    branches-ignore:
      - "master"
    paths:
      - "contracts/v0.1/**/VRFCoordinator.sol"
      - "contracts/v0.1/**/VRFConsumerBase.sol"
      - "contracts/v0.1/**/vrf/**"

jobs:
  build:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/integration')
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Install
        run: yarn contracts install

      - name: Compile
        run: yarn contracts compile

      - name: Build
        run: yarn contracts build

      - name: Build workspace dependency
        run: yarn vrf build

      - name: Run node and deploy
        run: npx hardhat node & yarn contracts deploy:localhost

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 6

      - name: Core - install
        run: yarn core install

      - name: Core - build
        run: yarn core build

      - name: Core - start listener
        run: yarn core start:listener:vrf &

      - name: Request random words
        run: yarn contracts request-vrf --network localhost

      - name: Core - start worker
        run: yarn core start:worker:vrf &

      - name: Core - start reporter
        run: yarn core start:reporter:vrf &
        env:
          PRIVATE_KEY: ${{ secrets.INTEGRATION_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.INTEGRATION_PUBLIC_KEY }}

      - name: Get random words
        run: yarn contracts get-vrf --network localhost
